"""Create data_loading_state table

Revision ID: 76aa27d9d783
Revises: 9b23e9cc271c
Create Date: 2025-07-07 22:53:49.409470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76aa27d9d783'
down_revision: Union[str, Sequence[str], None] = '9b23e9cc271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'data_loading_state',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('last_processed_index', sa.Integer, nullable=False, default=0)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
